version: '3.8'

services:
  graph:
    build: 
      context: ./server
    environment:
      POSTGRES_HOST: 'postgresdb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_NAME: 'muneddit'
      POSTGRES_PORT: '5432'
      REDIS_HOST: 'redisdb'
      FRONTEND_URL: 'http://localhost:8080'
    depends_on:
      - postgresdb
      - redisdb
    ports:
      - '3000:3000'

  frontend:
    build: 
      context: ./frontend
    depends_on:
      - graph
    ports:
      - '8080:8080'

  postgresdb:
    image: postgres
    volumes:
      - muneddit-postgres2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'admin'

  redisdb:
    image: redis
    volumes:
      - muneddit-redis:/data

volumes:
  muneddit-postgres2:
    driver: local
  muneddit-redis:
    driver: local
