version: "3.8"

services:
  app:
    build: .
    environment:
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_PASSWORD: "admin"
      DB_NAME: "muneddit"
      DB_PORT: "5432"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: postgres
    volumes:
      - muneddit-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin"

volumes:
  muneddit-postgres:
    driver: local